name: Angular CI
on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}

      - name: Use Node.js ${{ matrix.node-version }} & Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test
